name: Terraform Dev and Prod with Approvals

on:
  push:
    branches:
      -main 
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  dev-plan:
    name: Terraform Plan - Dev
    runs-on: ubuntu-latest
    environment: dev-plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::043309359569:role/OIDC_Github_access
          role-session-name: OIDC_Github_access
          aws-region: "us-east-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Select Dev Workspace
        run: terraform workspace select dev || terraform workspace new dev

      - name: Terraform Plan (Dev)
        run: terraform plan -var-file="dev.tfvars"

  dev-apply:
    name: Terraform Apply - Dev
    runs-on: ubuntu-latest
    needs: dev-plan
    environment: dev-apply
    steps:
      - uses: actions/checkout@v4
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::043309359569:role/OIDC_Github_access
          role-session-name: OIDC_Github_access
          aws-region: "us-east-1"

      - uses: hashicorp/setup-terraform@v3
      - run: terraform init

      - run: terraform workspace select dev
      - run: terraform apply -auto-approve -var-file="dev.tfvars"

  prod-plan:
    name: Terraform Plan - Prod
    runs-on: ubuntu-latest
    needs: dev-apply
    environment: Prod-plan
    steps:
      - uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::043309359569:role/OIDC_Github_access
          role-session-name: OIDC_Github_access
          aws-region: "us-east-1"

      - uses: hashicorp/setup-terraform@v3
      - run: terraform init

      - run: terraform workspace select prod || terraform workspace new prod
      - run: terraform plan -var-file="prod.tfvars"

  prod-apply:
    name: Terraform Apply - Prod
    runs-on: ubuntu-latest
    needs: prod-plan
    environment: prod-apply
    steps:
      - uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::043309359569:role/OIDC_Github_access
          role-session-name: OIDC_Github_access
          aws-region: "us-east-1"

      - uses: hashicorp/setup-terraform@v3
      - run: terraform init

      - run: terraform workspace select prod
      - run: terraform apply -auto-approve -var-file="prod.tfvars"
